ktor {
    deployment {
        port = 8080
        host = "0.0.0.0"
    }
    application {
        modules = [ com.osornofoodroutes.backend.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://ep-tiny-dawn-adjtq08k.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require"
    user = "neondb_owner"
    password = "npg_UHON2prVd0nP"
    driver = "org.postgresql.Driver"
}

jwt {
    secret = "osorno-food-routes-secret-key-2024"
    issuer = "osorno-food-routes"
    audience = "osorno-food-routes-app"
    realm = "Osorno Food Routes"
}
